# refers to `ansible` st2 integration pack:
# https://github.com/StackStorm/st2contrib/tree/master/packs/ansible
---
name: "chatops.ansible_playbook"
action_ref: "ansible.playbook"
description: "Run Ansible playbook on hosts"
formats:
  - display: "ansible_playbook"
    representation:
      - "ansible_playbook ( '{{playbook=/etc/ansible/playbook/ios_show_banner.yml}}' )"
      #{{ playbook }}"
result:
  format: |
    Ansible-playbook command `{{ execution.parameters.playbook }}` result: {~}
    {% if execution.result.stderr %}*Stdout:* {% endif %}
    ```{{ execution.result.stdout }}```
    {% if execution.result.stderr %}*Stderr:* ```{{ execution.result.stderr }}```{% endif %}
  extra:
    slack:
      color: "{% if execution.result.succeeded %}good{% else %}danger{% endif %}"
